---
title: "SBRT"
author: ''
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r global, include=FALSE}
dir_app<-"/home/sbrt/shiny/sbrt/"
# load data in 'global' chunk so it can be shared by all users of the dashboard
#source(paste0(dir_app,"relatorio_resposta/carega_pacotes.R"))
#carrega.pacote(paste0(dir_app,"relatorio_resposta/pacotes.txt"))
library(tidytext)
library(dplyr)
library(dendextend)
library(shinyWidgets)
library(dplyr)
library(stringr)
library(flexdashboard)
library(shiny)
library(shinythemes)
library(DT)
#packrat::unbundle("/home/micael/repositorios/github/textmining-sbrt/pacotes.tar.gz","/home/micael/repositorios/github/textmining-sbrt")

#library(biclust)
load(paste0(dir_app,"relatorio_resposta/base/sbrt_vis_10.RData"))
set.seed(1)

#Seleção dos 100 dossiês mais relevantes por tópico.
respostas_topic<-respostas_topic %>%
  group_by(topic)%>%filter(gamma>0.5)
respostas_topic$periodo<-gsub(regex("(\\d+/\\d+/)", dotall = TRUE),"",respostas_topic$DATA_CRIACAO)%>%
as.numeric()
#names(respostas_topic)<-c("Resposta", "Título", "Categoria atual do SBRT", "Assunto", "topic", "Gamma")

#Seleção dos 1000 termos mais relevantes por tópico.
terms_sbrt<-terms_sbrt%>%
  group_by(topic) %>% slice(1:1000)%>%
  ungroup()
names(terms_sbrt)<-c("topic", "Termo", "Beta")

respostas_total<-nrow(respostas_topic)
periodo<- respostas_topic$periodo%>%unique()%>%sort()
topics_selector<-as.list(1:length(labels_topics_selector))
names(topics_selector)<-labels_topics_selector
```

Inputs {.sidebar}
====================================================================================

```{r include=FALSE}
dropdownButton <- function(label = "", status = c("default", "primary", "success", "info", "warning", "danger"), ..., width = NULL) {

  status <- match.arg(status)
  # dropdown button content
  html_ul <- list(
    class = "dropdown-menu",
    style = if (!is.null(width)) 
      paste0("width: ", validateCssUnit(width), ";"),
    lapply(X = list(...), FUN = tags$li, style = "margin-left: 10px; margin-right: 10px;")
  )
  # dropdown button apparence
  html_button <- list(
    class = paste0("btn btn-", status," dropdown-toggle"),
    type = "button", 
    `data-toggle` = "dropdown"
  )
  html_button <- c(html_button, list(label))
  html_button <- c(html_button, list(tags$span(class = "caret")))
  # final result
  tags$div(
    class = "dropdown",
    do.call(tags$button, html_button),
    do.call(tags$ul, html_ul),
    tags$script(
      "$('.dropdown-menu').click(function(e) {
      e.stopPropagation();
});")
  )
  }
```



```{r include=FALSE}
#obervers para o checkbox dos estados
  #output$res1 <- renderPrint({
  #  input$check1
  #})

  # Sorting asc
  observeEvent(input$a2z, {
    updateCheckboxGroupInput(
      session = session, inputId = "check2", choices = unique(respostas_topic$UF_ORIG), selected = input$check2
    )
  })
  # Sorting desc
  observeEvent(input$z2a, {
    updateCheckboxGroupInput(
      session = session, inputId = "check2", choices = rev(unique(respostas_topic$UF_ORIG)), selected = input$check2
    )
  })
  output$res2 <- renderPrint({
    input$check2
  })
  # Select all / Unselect all
  observeEvent(input$all, {
    if (is.null(input$check2)) {
      updateCheckboxGroupInput(
        session = session, inputId = "check2", selected = unique(respostas_topic$UF_ORIG)
      )
    } else {
      updateCheckboxGroupInput(
        session = session, inputId = "check2", selected = ""
      )
    }
  })
```



```{r include=FALSE}
#obervers para o checkbox das instituicoes
  #output$res1 <- renderPrint({
  #  input$check1
  #})

  # Sorting asc
  observeEvent(input$a2z, {
    updateCheckboxGroupInput(
      session = session, inputId = "check3", choices = unique(respostas_topic$INST), selected = input$check3
    )
  })
  # Sorting desc
  observeEvent(input$z2a, {
    updateCheckboxGroupInput(
      session = session, inputId = "check3", choices = rev(unique(respostas_topic$INST)), selected = input$check3
    )
  })
  output$res2 <- renderPrint({
    input$check3
  })
  # Select all / Unselect all
  observeEvent(input$all_inst, {
    if (is.null(input$check3)) {
      updateCheckboxGroupInput(
        session = session, inputId = "check3", selected = unique(respostas_topic$INST)
      )
    } else {
      updateCheckboxGroupInput(
        session = session, inputId = "check3", selected = ""
      )
    }
  })
```


```{r}
fluidPage(theme = shinytheme("united"),
fluidRow(
  #br(),
column(width = 12, align="left",
tags$h1("Filtros"),

#selector de tópicos
tags$h4("Tópico"),
selectInput("topicnum",
label = "Selecione um tópico:", 
choices=topics_selector,
selected = topics_selector[[1]], 
width = "100%"),


#selector de estado
tags$h4("Origem da Solicitação"),
tags$h5("Selecione um ou mais estados:"),
dropdownButton(
label = "Estados", 
status = "default", 
width = 100,

actionButton(
inputId = "a2z", 
label = "A - Z", 
icon = icon("sort-alpha-asc")),

actionButton(
inputId = "z2a",
label = "Z - A",
icon = icon("sort-alpha-desc")),
#br(),

actionButton(
inputId = "all",
label ="Todos/Nenhum"),

checkboxGroupInput(inputId = "check2",
label = "Selecione",
choices =unique(respostas_topic$UF_ORIG),
selected = unique(respostas_topic$UF_ORIG)
)
),
#br(),

#selector de instituição
tags$h4("Instituição Responsável"),
tags$h5("Selecione um ou mais instituições:"),
dropdownButton(
label = "Instituição", 
status = "default", 
width = 100,

actionButton(
inputId = "a2z", 
label = "A - Z", 
icon = icon("sort-alpha-asc")),

actionButton(
inputId = "z2a",
label = "Z - A",
icon = icon("sort-alpha-desc")),
#br(),

actionButton(
inputId = "all_inst",
label ="Todos/Nenhum"),

checkboxGroupInput(inputId = "check3",
label = "Selecione",
choices =unique(respostas_topic$INST),
selected = unique(respostas_topic$INST)
)
),

#br(),

tags$h4("Ano de Criação"),
#selector de intervalo de anos
sliderInput(
"ano", "Selecione o intervalo de anos:",
min = min(periodo),
max = max(periodo),
value = c(min(periodo),max(periodo)),
sep="")
                            
                            
                            
                            
)
)
)
```



Documentos
====================================================================================

Row
-----------------------------------------------------------------------
### Respostas Selecionadas


```{r include=FALSE}
#inputs
num <- reactive(as.integer(input$topicnum))
uf<-reactive(input$check2)
insti<-reactive(input$check3)
ano_inicio<-reactive(as.numeric(input$ano[1]))
ano_fim<-reactive(as.numeric(input$ano[2]))
categoria<-reactive(input$categ)
```


```{r}
renderValueBox(
valueBox(as.character(respostas_n()), icon = "fa-file-alt"))
```


### Proporção do total de respostas do tópico
```{r}
porcentagem<-reactive({round(respostas_n()/n_respostas_topico()*100,digits = 2)})
renderGauge(
  #per<-round(respostas_total/respostas_n()*100),
  gauge(porcentagem(), min = 0, max = 100, symbol = '%')
)
```


Row {.tabset}
-----------------------------------------------------------------------



### Respostas do Tópico

```{r}
respostas_tbl<-reactive({respostas_topic%>%
  filter(topic==num())%>%
  filter(UF_ORIG %in% uf())%>%
  filter(INST %in% insti())%>%
  #filter(periodo>=ano_inicio()|periodo<=ano_fim())%>%
  filter(periodo>=ano_inicio())%>%
  filter(periodo<=ano_fim())%>%
  #filter(str_detect(DATA_CRIACAO, regex("(\\d+/\\d+/2008)", dotall = TRUE)))%>%
  #filter(`Categoria atual do SBRT` %in% categoria() )%>%
  ungroup()%>%
  select(-topic, -AUTOR_QT,-COD_QT,-CNAE_SUB_RT,-periodo)
})

n_respostas_topico<-reactive({respostas_topic%>%
  filter(topic==num())%>%nrow()})
```




```{r}

#Tabela de respostas por tópico
renderDataTable({
DT::datatable(
respostas_tbl(),
fillContainer = TRUE,
autoHideNavigation = FALSE,
colnames=c("ID", "Origem da solicitação",
           "Intituição Responsável", 
            "CNAE subclasse descrição",
           "Titulo da RT", "Descrição da RT",
            "Data de criação", "Gamma"),
options = list(
scrollY='400px',
scrollX='400px',
bPaginate = TRUE,
language = list(
url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese-Brasil.json'),
columnDefs = list(
list(
className = 'dt-center', 
argets = 1:8))))%>%
formatRound(
columns=c("gamma"),
digits=3)%>%
formatStyle(c("document", "UF_ORIG", "INST",
              "CNAE_SUB_DESCR", "TITULO_RT",
              "DESCR_RT", "DATA_CRIACAO", "gamma"),
              `text-align` = "center")
})
```

```{r include=FALSE}
#pegando o número de respostas selecionadas
respostas_n<-reactive({
  as.numeric(respostas_tbl()
             %>%ungroup()
             %>%nrow())
})

```




### Dendrograma


### Extração de Termos

```{r}
termos<-reactive({

dir_app<-"/home/sbrt/shiny/sbrt"
setwd(dir_app)
source("scripts/respostas/get_funs.R")
options(java.parameters="-Xmx2g")
library(dfrtopics)
library(tidytext)
library(tidyverse)
library(mallet)
library(dendextend)
library(readr)

#Diretórios dos arquivos necessários
respostas_dir<-"/mnt/dados/sbrt/dados/sbrt_txts/respostas_txt/"
#respostas_dir<-"/home/micael/R_envs/text-mining/dados/sbrt_txts/respostas_txt"
metadados_dir<-"/mnt/dados/sbrt/metadados/metadados_RT.csv"
stop_words_sbrt<-"/mnt/dados/sbrt/dados/metadados/stop_words_sbrt.txt"




docs_interesse<-paste0(respostas_dir,respostas_tbl()$document,".txt")

#Leitura das stopwords.
sw<-readr::read_lines(stop_words_sbrt)

#Leitura e pré-processamento dos documentos.
txtdf<-get_txt(docs_interesse)

#Criação de um dataframe dos metadados dos documentos.
metadados<-readr::read_csv2(metadados_dir)

#Preaparação dos documentos para criação do modelo LDA.
instance_mallet<-make_instances(txtdf, stoplist_file = stop_words_sbrt)


#Criação do modelo LDA de acordo com o número de tópicos encontrado no processo anterior.
best_model<-train_model(instance_mallet,n_topics = 1, metadata = metadados, seed = 12345)
best_model$doc_ids<-doc_ids(best_model)


#Gera dataframe de termos por tópico.
terms_sbrt_filtered<-tidy(best_model$model, matrix = "beta")%>%
  arrange(desc(beta))

terms_sbrt_filtered%>%select(-topic)

}
)


```

```{r}
#Tabela de respostas por tópico
renderDataTable({
DT::datatable(
termos(),
fillContainer = TRUE,
autoHideNavigation = FALSE,
colnames=c("Termo", "Beta"),
options = list(
scrollY='400px',
scrollX='400px',
bPaginate = TRUE,
language = list(
url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Portuguese-Brasil.json'),
columnDefs = list(
list(
className = 'dt-center', 
argets = 1:2))))%>%
#formatRound(
#columns=c("beta"),
#digits=3)%>%
formatStyle(c("term", "beta"),
              `text-align` = "center")
})
```


### Tokens

```{r}
renderTable({
  
dir_app<-"/home/sbrt/shiny/sbrt/"
setwd(dir_app)
source("scripts/respostas/get_funs.R")
options(java.parameters="-Xmx2g")
library(dfrtopics)
library(tidytext)
library(tidyverse)
library(mallet)
library(dendextend)
library(readr)

#Diretórios dos arquivos necessários
respostas_dir<-"/mnt/dados/sbrt/dados/sbrt_txts/respostas_txt/"
#respostas_dir<-"/home/micael/R_envs/text-mining/dados/sbrt_txts/respostas_txt"
metadados_dir<-"/mnt/dados/sbrt/metadados/metadados_RT.csv"
stop_words_sbrt<-"/mnt/dados/sbrt/metadados/stop_words_sbrt.txt"




docs_interesse<-paste0(respostas_dir,respostas_tbl()$document,".txt")

#Leitura das stopwords.
sw<-readr::read_lines(stop_words_sbrt)

#Leitura e pré-processamento dos documentos.
txtdf<-get_txt(docs_interesse)
  
 tokens <- txtdf %>%
    tidytext::unnest_tokens(word, text)
  
  # find document-word counts
  word_counts <- tokens %>%
    filter(!(nchar(word) == 1))%>% 
    filter(!word %in% sw) %>%
    count(id, word, sort = TRUE) %>%
    ungroup()
  word_counts%>%select(-id,)%>%count(word)%>%arrange(desc(n))
  
}
)


```



Termos
====================================================================================


Row
-----------------------------------------------------------------------

### Dendograma
    
```{r}
num <- reactive(as.integer(input$topicnum))

renderPlot({
par(mar = c(0,0,0,0))
dendrograma_terms %>% 
  set("branches_k_color", k = best_topic)%>% 
  set("labels_cex", 1) %>%
  set("leaves_cex",0.2)%>%
  set("hang_leaves",0.1)%>%
  set("branches_lwd", 2)%>%
  plot(horiz=T, axes=F)
})

```






Row {.tabset}
-----------------------------------------------------------------------



### Hierarquia dos termos
    
```{r}
renderTable(
terms_sbrt%>%
  filter(topic==num())%>%
  select(-topic)#, digits=6
)
```



